name: using cache-input
on:
    workflow_dispatch: 
        inputs:
            using-cache:
                description: Whether to execute cache step
                type: boolean
                default: true
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: react-app
        steps:
            #checkout code
            - name: Checkout code
              uses: actions/checkout@v4
            #Setup Node  
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
        #Install dependencies
            - name: Install dependencies
              run: npm ci
        #Testing
            - name: testing
              run: npm run test 
        #Building
            - name: Building
              run: npm run build 
        #Deploying to nonprod
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"

           