name: using cache-input
on:
    workflow_dispatch: 
        inputs:
            using-cache:
                description: Whether to execute cache step
                type: boolean
                default: true
            node-choice:
                type: choice
                description: Provide Node version
                options:
                  - 18.x
                  - 20.x
                  - 21.x
                default: 20.x    
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: react-app
        steps:
            #checkout code
            - name: Checkout code
              uses: actions/checkout@v4
            #Setup Node  
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{inputs.node-choice}}
            - name: Download cached dependencies
              id: cache
              if: ${{inputs.using-cache}}
              uses: actions/cache@v3
              with:
                key: deps-node-modules-${{hashFiles('react-app/package-lock.json')}}
                path: react-app/node_modules        
        #Install dependencies
            - name: Install dependencies
              if: ${{steps.cache.outputs.cache-hit != 'true'}}
              run: npm ci
        #Testing
            - name: testing
              run: npm run test 
        #Building
            - name: Building
              run: npm run build 
        #Deploying to nonprod
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"

           